### ISSUE TITLE
나스선생님 문안인사드려요오오오오

### ISSUE THREAD

**Issue by moto6** [Malloc72P/sidedish#22]
나스선생니이이임 ㅋㅋㅋ 잘지내시죠 ㅋㅋㅋㅋㅋ 코드탐방왔다가 문안인사드려오오오오! 화이팅하십쇼!!! ㅋㅋㅋ

**Comment by Malloc72P** [comment]
안녕하세요오오오오오오오오 잘 지내다가 가십쇼오오오오오오오
